### ISSUE TITLE
Deprection of reshape

### ISSUE THREAD

**Issue by esraa-saleh** [CSchoel/nolds#10]
When using the Hurst Exponent function, I got the following, numpy related warning:

FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead

**Comment by esraa-saleh** [comment]
I see . Thank you for your response ! 
(and also for building this project, I learned a lot through it :) )

**Comment by CSchoel** [comment]
Thank you for your kind words and your feedback. :smile: 

Quick hint: I just released version 0.5.1 that should enable you to use pandas objects as input for nolds algorithms. Please let me know if anything still goes wrong.
