### ISSUE TITLE
Sampen returns inf on certain vectors

### ISSUE THREAD

**Issue by dorian821** [CSchoel/nolds#14]
Hi Christopher, 

Great module! I'm just starting to play around with it. I'm calculating a rolling sampen on a single vector using a window 60 points wide, and I'm noticing that on some of the windows, the method returns inf. I've confirmed that there are no nan or inf values in my data array. The odd thing is that if I expand/contract the window slightly in the regions where infs are generated it returns a normal value. What might be the reason for this?

my emb_dim is 2 and an example array producing inf is below:

```
array([ 3.97897359,  2.57013282,  1.45842405,  2.68826392,  7.31447341,
        5.78199552,  6.56846706,  4.87548617,  6.06460367,  5.98447964,
        5.10990579,  3.98096388,  7.59746302, -0.07659857,  3.16797671,
        5.77983908,  3.02430642,  4.95546237,  6.07352899,  8.09528219,
        5.68092534,  5.57796569,  5.78986204,  6.45694346,  5.51082336,
        3.62068115,  5.45598895,  4.73611244,  6.61318103,  5.00210034,
        5.06841458,  4.11860764,  5.08174585,  4.93897692,  7.28100181,
        4.73825745,  4.68800652,  6.07565328,  5.53210218,  5.16863708,
        2.71207448,  3.51531164,  6.94629671,  3.8649315 , -0.41799253,
        2.6010292 ,  2.50768146,  4.78871296, -3.20448453,  4.32893052,
        4.97199359,  6.514833  ,  2.73325493,  1.86146005,  5.80707187,
        3.37129316,  0.34194481,  3.44398483,  0.75766866,  0.81707214])
```

Thanks!

**Comment by CSchoel** [comment]
I just noticed that I only responded to this issue via Mail. For future reference here is the answer:

>Hi Dorian,
>
>thanks for the praise. =) You get inf as a result if there are no subsequence pairs of length emb_dim + 1 with a difference smaller than the tolerance. You can see the problem if you use the keyword argument debug_plot=True (see attached figure). For your data you have 25 pairs of length emb_dim, but 0 pairs of length emb_dim + 1. The red line in the plot shows the tolerance value. The final calculation step would be "-np.log(0.0 / 25.0)" which yields the result inf and produces a warning. In nolds I return the inf-result, but discard the warning. Maybe I should produce my own warning that hints at the actual problem.
>
>Long story short, I suppose you would get more consistent results if you chose a fixed value for the tolerance parameter instead of the default choice which calculates a different tolerance for each window (which sometimes seems to be too low for your data).
>
>Regards
>Christopher

![Figure_1](https://user-images.githubusercontent.com/10725211/74108685-201d2e80-4b7d-11ea-82e7-06c1b6b7c1a4.png)
