### ISSUE TITLE
N-D support?

### ISSUE THREAD

**Issue by toinsson** [CSchoel/nolds#15]
Hello, 

I am interested in using nolds for the analysis of N-dimensional times-series. 

I was wondering if there is a case for developping the support of N-dimensional data in the algorithms you have implemented (I'll be doing that work and providing a pull request down the line.) Or if running the algo on each dimensions separately and analysing the results separately makes more sense.

What do you think?

**Comment by CSchoel** [comment]
Hi toinsson,

currently the focus of nolds is exclusively on one-dimensional time series. The reason for this is mainly that I only work with one-dimensional time series myself and I have zero experience with the N-dimensional case.

I think support for N-dimensional data would be very interesting, but I only can dedicate a very limited amount of my time to nolds. You can of course send me a pull request of your implementations and I would be very glad for that, but it may take me quite some time to actually review the code.

As I said I do not have any experience with the multidimensional case, but I think I remember that there are extensions of some of the algorithms in nolds for multiple dimension (DFA comes to mind). I think it is important to look at the research in the area you are interested in and to see which algorithms are used by other researchers. The selection of algorithms for nolds was also mainly based on one paper that lists useful non-linear methods for HRV analysis.

**Comment by toinsson** [comment]
hello, thanks a lot for your reply. 
I realised a bit later that it might be harder than expected to implement this.
This is best closed for the moment.
