### ISSUE TITLE
cannot convert float infinity to integer

### ISSUE THREAD

**Issue by Aurora33** [CSchoel/nolds#21]
hi,
When i call nolds.lay_e with my datas, i got "cannot convert float infinity to integer" because of "diffs[i] = float('inf')" in the code. Do you tell me how to fix it ?

Thanks !

**Comment by CSchoel** [comment]
Are your input data integers? If so, you will need to convert them to a float array:

```
data = numpy.asarray(data, dtype=numpy.float32)
```

I will fix this in the future by adding the `dtype` argument to the `asarray` call that is already issued in `lyap_e`.
